[package]
name = "papernest"
version = "0.1.3"
description = "PaperNest - a minimalist WYSIWYG Markdown editor"
authors = ["baihejiangnan"]
edition = "2021"
rust-version = "1.85"

[lib]
name = "papernest_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-opener = "2"
tauri-plugin-dialog = "2"
tauri-plugin-single-instance = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
toml = "0.8"
comrak = "0.54"
anyhow = "1"
reqwest = { version = "0.12", features = ["socks", "json"] }
base64 = "0.22"
semver = "1"
minisign-verify = "0.2.5"
tempfile = "3"
ammonia = "4"

[target.'cfg(not(windows))'.dependencies]
trash = "5.2"

[dev-dependencies]
trash = "5.2"

[target.'cfg(windows)'.dependencies]
winreg = "0.55"
windows = { version = "0.62", features = ["Win32_Foundation", "Win32_System_Com", "Win32_UI_Shell"] }
windows-core = "0.62"
windows-sys = { version = "0.61", features = ["Win32_Foundation", "Win32_System_Com", "Win32_UI_Shell", "Win32_UI_Shell_Common", "Win32_UI_WindowsAndMessaging"] }

[profile.release]
codegen-units = 1
lto = true
opt-level = "s"
panic = "abort"
strip = true
